<a href="https://colab.research.google.com/github/themysterysolver/PYTHON_BASICS/blob/main/SCIPY/SCIPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## SciPy
- SciPy is a scientific computation library that uses NumPy underneath.
- SciPy stands for Scientific Python.

In [ ]:
import scipy
print(scipy.__version__)

1.13.1


## CONSTANTS
- PI is an example of a scientific constant.

In [ ]:
from scipy import constants
print(constants.pi)

3.141592653589793


In [ ]:
print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', '

Unit Categories
The units are placed under these categories:

1. Metric
2. Binary
3. Mass
4. Angle
5. Time
6. Length
7. Pressure
8. Volume
9. Speed
10. Temperature
11. Energy
12. Power
13. Force

In [ ]:
print(constants.centi,constants.kilo,constants.nano,constants.micro,constants.mega,constants.pico) # mass in m

0.01 1000.0 1e-09 1e-06 1000000.0 1e-12


In [ ]:
print(constants.sec,constants.year) # time in s

## Optimizers in SciPy

- Optimizers are a set of procedures defined in SciPy that either find the **minimum** value of a function, or the **root** of an equation.
- **NumPy** is capable of finding roots for *polynomials and linear equations*.
- Optimizing Functions:Essentially, all of the algorithms in Machine Learning are nothing more than a *complex equation that needs to be minimized with the help of given data*.
- `optimize.root` function.
- This function takes two required arguments:
    - fun - a function representing an equation.
    - x0 - an initial guess for the root.

- The function returns an ***object*** with information regarding the solution.
- The actual solution is given under `attribute x` of the returned object

- it can not find roots for non linear equations, like this one:x + cos(x)
  - Yes, non-linear equations can have solutions. A non-linear equation is one in which the relationship between the variables is not linear (i.e., it cannot be represented by a straight line). These equations can have various forms, such as quadratic, cubic, exponential, logarithmic, trigonometric, and more.
  - Solutions of Non-linear Equations:
      - Single Solution: Some non-linear equations may have only one solution. For example, a simple quadratic equation
      - Multiple Solutions: Other non-linear equations may have multiple solutions.
      - No Real Solution: Some non-linear equations may have no real solution, but they might have complex solutions.
      - Infinite Solutions: Certain non-linear equations or systems can have infinitely many solutions, depending on their nature.

In [ ]:
from scipy.optimize import root
from math import cos
def eqn(x):
  return x+cos(x)
rt=root(eqn,0)
print(rt.x)
print(rt)

[-0.73908513]
 message: The solution converged.
 success: True
  status: 1
     fun: [ 0.000e+00]
       x: [-7.391e-01]
  method: hybr
    nfev: 9
    fjac: [[-1.000e+00]]
       r: [-1.674e+00]
     qtf: [-2.668e-13]


<ipython-input-1-6882a9c84287>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return x+cos(x)


## Minimizing a Function
- A function, in this context, represents a curve, curves have high points and low points.
- High points are called *maxima*.
- Low points are called *minima*.
- The highest point in the whole curve is called *global maxima*, whereas the rest of them are called *local maxima*.
- The lowest point in whole curve is called *global minima*, whereas the rest of them are called *local minima*.
- We can use `scipy.optimize.minimize()` function to minimize the function.
- The minimize() function takes the following arguments:
    - fun - a function representing an equation.
    - x0 - an initial guess for the root.
    - method - name of the method to use. Legal values:
          CG - Conjugate Gradient
          BFGS - Broyden-Fletcher-Goldfarb-Shanno
          Newton-CG - Newton-Conjugate Gradient
          L-BFGS-B - Limited-memory BFGS with Box constraints
          TNC - Truncated Newton Conjugate-Gradient
          COBYLA - Constrained Optimization BY Linear Approximations
          SLSQP - Sequential Least Squares Programming
    - callback - function called after each iteration of optimization.
    - options - a dictionary defining extra params

In [ ]:
from scipy.optimize import minimize
def eqn1(x):
  return x**2+x+1
rt1=minimize(eqn,0,method="BFGS")
print(rt1.x)
print(rt1)

[-1.06232897e+08]
  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: -106232897.39088017
        x: [-1.062e+08]
      nit: 2
      jac: [ 0.000e+00]
 hess_inv: [[ 5.214e+00]]
     nfev: 42
     njev: 21


<ipython-input-1-6882a9c84287>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return x+cos(x)


## Sparse Data
- Sparse data is data that has mostly unused elements (elements that don't carry any information ).
- Sparse Data: is a data set where most of the item values are zero.
- Dense Array: is the opposite of a sparse array: most of the values are not zero.
- In scientific computing, when we are dealing with **partial derivatives** in linear algebra we will come across sparse data.
- `scipy.sparse` that provides functions to deal with sparse data.
- There are primarily two types of sparse matrices that we use:
  - *CSC* - Compressed Sparse Column. For efficient arithmetic, fast column slicing.
  - *CSR* - Compressed Sparse Row. For fast row slicing, faster matrix vector products

In [24]:
import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([0,0,0,0,0,0,1,1,0,2,0,0,9,100])
print('   (r,c)\t value\n',csr_matrix(arr))#(row,col) and value

   (r,c)	 value
   (0, 6)	1
  (0, 7)	1
  (0, 9)	2
  (0, 12)	9
  (0, 13)	100


In [25]:
csr_mat=csr_matrix(arr)
print(csr_mat.data)
print(csr_mat.count_nonzero)
#vague-read it once more!
csr_mat.eliminate_zeros()
csr_mat.sum_duplicates()
print(csr_mat)
newarr=csr_mat.tocsc()
print('-------------')
print(newarr)

[  1   1   2   9 100]
<bound method _data_matrix.count_nonzero of <1x14 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>>
  (0, 6)	1
  (0, 7)	1
  (0, 9)	2
  (0, 12)	9
  (0, 13)	100
-------------
  (0, 6)	1
  (0, 7)	1
  (0, 9)	2
  (0, 12)	9
  (0, 13)	100


# GRAPHS
- graph DS,`scipy.sparse.csgraph`.
- Adjacency matrx is a **n*n** matrix(a sq matrix)
Parameters:
-directed (optional): A boolean indicating whether the graph is directed (True) or undirected (False). The default is True.
- connection (optional): Specifies the type of connections to consider:

  - 'weak': For directed graphs, considers weakly connected components (ignores edge directions).
  - 'strong': For directed graphs, considers strongly connected components (respects edge directions).
  - This parameter is only relevant when directed=True.
- return_labels (optional): A boolean indicating whether to return the component labels for each node. Default is True.

In [26]:
from scipy.sparse.csgraph import connected_components
graph=np.array([
    [0, 1, 0, 0, 0, 0, 0, 0],  # Node 0 connected to Node 1
    [1, 0, 0, 0, 0, 0, 0, 0],  # Node 1 connected to Node 0
    [0, 0, 0, 1, 0, 0, 0, 0],  # Node 2 connected to Node 3
    [0, 0, 1, 0, 0, 0, 0, 0],  # Node 3 connected to Node 2
    [0, 0, 0, 0, 0, 1, 0, 0],  # Node 4 connected to Node 5
    [0, 0, 0, 0, 1, 0, 0, 0],  # Node 5 connected to Node 4
    [0, 0, 0, 0, 0, 0, 0, 1],  # Node 6 connected to Node 7
    [0, 0, 0, 0, 0, 0, 1, 0], ])
newg=csr_matrix(graph)
print(connected_components(newg))
no_of_comp,labels=connected_components(newg)
print(no_of_comp,labels)

(4, array([0, 0, 1, 1, 2, 2, 3, 3], dtype=int32))
4 [0 0 1 1 2 2 3 3]


## Dijkstras algorithm
1. csgraph: The graph to search. It should be in the form of a 2D array (adjacency matrix) or sparse matrix.
2. directed: Boolean value to indicate if the graph is directed. Default is True.
3. indices: A list or array specifying the starting points for the search (optional). Default is None, meaning the search starts from all nodes.
4. limit: A value that can restrict the search to a limited number of
5. iterations. Default is None, which means no limit.
6. return_predecessors: Boolean value that, if True, returns an array of predecessors along the shortest paths.
7. unweighted: Boolean indicating whether to treat the graph as unweighted. Default is False.
8. min_heap: Boolean to decide whether to use a min-heap optimization. Default is True.
9. dtype: The data type of the output. Default is float


`scipy.sparse.csgraph.dijkstra`, returns two arrays:
- distances: An array of the shortest distances from the specified source node to all other nodes in the graph. If a node is not reachable from the source, its distance will be inf (infinity).
- predecessors (optional): An array of the predecessors for each node in the shortest path from the source node. This array allows you to reconstruct the shortest path.

In [27]:
from scipy.sparse.csgraph import dijkstra
dgraph=np.array( [[0, 4, 0, 0, 0, 0, 0, 8, 0],
               [4, 0, 8, 0, 0, 0, 0, 11, 0],
               [0, 8, 0, 7, 0, 4, 0, 0, 2],
               [0, 0, 7, 0, 9, 14, 0, 0, 0],
               [0, 0, 0, 9, 0, 10, 0, 0, 0],
               [0, 0, 4, 14, 10, 0, 2, 0, 0],
               [0, 0, 0, 0, 0, 2, 0, 1, 6],
               [8, 11, 0, 0, 0, 0, 1, 0, 7],
               [0, 0, 2, 0, 0, 0, 6, 7, 0]
               ])
dgraph=csr_matrix(dgraph)
print(dijkstra(dgraph,indices=0,return_predecessors=True))
distances,predecessor=dijkstra(dgraph,indices=0,return_predecessors=True)
print(distances,predecessor)

(array([ 0.,  4., 12., 19., 21., 11.,  9.,  8., 14.]), array([-9999,     0,     1,     2,     5,     6,     7,     0,     2],
      dtype=int32))


In [28]:
from scipy.sparse.csgraph import floyd_warshall,bellman_ford,depth_first_order,breadth_first_order
print(depth_first_order(dgraph,0))
print(breadth_first_order(dgraph,0))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32), array([-9999,     0,     1,     2,     3,     4,     5,     6,     7],
      dtype=int32))
(array([0, 1, 7, 2, 6, 8, 3, 5, 4], dtype=int32), array([-9999,     0,     1,     2,     3,     2,     7,     0,     7],
      dtype=int32))
