<a href="https://colab.research.google.com/github/themysterysolver/PYTHON_BASICS/blob/main/NUMPY/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy(Numerical Python)
- NumPy is used for working with arrays.
- It also has functions for working in domain of **linear algebra, fourier transform, and matrices.**
- In Python we have *lists* that serve the purpose of arrays, but they are **slow to process**.
- The **array object** in NumPy is called `ndarray`.

# Why is NumPy Faster Than Lists?
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
- This behavior is called locality of reference in computer science.

In [4]:
import numpy as np
print(np.__version__)

1.26.4


In [5]:
arr=np.array([i for i in range(1,6)])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [6]:
narr=[[False]*3 for _ in range(2)]
print(type(narr),narr)
narr=np.array(narr)
print(type(narr),narr)

<class 'list'> [[False, False, False], [False, False, False]]
<class 'numpy.ndarray'> [[False False False]
 [False False False]]


In [11]:
print(narr.ndim)#dimension of array
narr1=np.array([1,2,3,4],ndmin=5)#define the number of dimensions by using the ndmin argument.
print(narr1,narr1.ndim)

2
[[[[[1 2 3 4]]]]] 5


In [13]:
arr2D=np.array([[1,2,3,4],[5,6,7,8]])
arr1D=np.array([1,2,3,4])
print(arr1D,'\n',arr2D)

[1 2 3 4] 
 [[1 2 3 4]
 [5 6 7 8]]


#### Access 2-D Arrays
- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

In [16]:
print(arr2D[1,2],arr2D[-1,-1])#negative indexing to access an array from the end.

7 8


In [18]:
arrx = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(arrx[-1,0])

50
